-- Supabase Schema DDL for OnePath Enrollment Manager

-- 1. Crèche Rooms Table
CREATE TABLE IF NOT EXISTS public.rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    min_age_months INT NOT NULL,
    max_age_months INT NOT NULL,
    capacity INT NOT NULL,
    staff_ratio TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Applications (Prospective Children) Table
CREATE TABLE IF NOT EXISTS public.applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_first_name TEXT NOT NULL,
    child_last_name TEXT NOT NULL,
    date_of_birth DATE NOT NULL,
    requested_start_date DATE NOT NULL,
    parent_name TEXT NOT NULL,
    parent_email TEXT NOT NULL,
    parent_phone TEXT DEFAULT '',
    enquiry_source TEXT DEFAULT 'Website',
    stage TEXT DEFAULT 'interest_captured',
    room_id BIGINT REFERENCES public.rooms(id) ON DELETE SET NULL,
    days_requested TEXT DEFAULT 'Full-time (5 Days)',
    sibling_priority BOOLEAN DEFAULT FALSE,
    deposit_paid BOOLEAN DEFAULT FALSE,
    deposit_amount NUMERIC DEFAULT 0.00,
    medical_notes TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    last_contact_date TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Follow-Up Tasks Table
CREATE TABLE IF NOT EXISTS public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL REFERENCES public.applications(id) ON DELETE CASCADE,
    task_type TEXT NOT NULL,
    title TEXT NOT NULL,
    due_date DATE NOT NULL,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Sync Audit Logs Table
CREATE TABLE IF NOT EXISTS public.sync_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL REFERENCES public.applications(id) ON DELETE CASCADE,
    target_platform TEXT NOT NULL,
    status TEXT NOT NULL,
    payload JSONB,
    response_message TEXT,
    synced_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) & Allow Public Read/Write for Demo
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sync_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read/write access to rooms" ON public.rooms FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write access to applications" ON public.applications FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write access to tasks" ON public.tasks FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write access to sync_logs" ON public.sync_logs FOR ALL USING (true) WITH CHECK (true);

-- Seed Initial Crèche Rooms
INSERT INTO public.rooms (name, min_age_months, max_age_months, capacity, staff_ratio) VALUES
('Baby Room (Buttercups)', 0, 12, 9, '1:3'),
('Wobblers & Toddlers (Daisies)', 12, 24, 12, '1:5'),
('Playgroup & Junior Preschool (Sunflowers)', 24, 36, 18, '1:6'),
('ECCE Preschool Room A (Oak)', 36, 60, 22, '1:11')
ON CONFLICT DO NOTHING;

-- Seed Sample Irish Prospective Enquiries
INSERT INTO public.applications (
  child_first_name, child_last_name, date_of_birth, requested_start_date,
  parent_name, parent_email, parent_phone, enquiry_source, stage, room_id,
  days_requested, sibling_priority, deposit_paid, deposit_amount, medical_notes, notes
) VALUES 
('Liam', 'O’Connor', '2025-10-15', '2026-09-01', 'Siobhan O’Connor', 'siobhan.oc@example.ie', '+353 87 123 4567', 'Website', 'interest_captured', 1, 'Full-time (5 Days)', TRUE, FALSE, 0, 'No known allergies', 'Enquired via online form.'),
('Aoife', 'Murphy', '2025-04-10', '2026-08-15', 'Ciarán Murphy', 'ciaran.m@example.ie', '+353 86 987 6543', 'Email', 'classified', 2, '3 Days (Mon, Wed, Fri)', FALSE, FALSE, 0, 'Mild eczema - cream required', 'Age classified as Wobbler.'),
('Cillian', 'Walsh', '2024-11-20', '2026-09-01', 'Fiona Walsh', 'fiona.walsh@example.ie', '+353 85 456 7890', 'Phone', 'waiting_list', 2, 'Full-time (5 Days)', FALSE, FALSE, 0, 'Lactose sensitive', 'Added to waiting list.'),
('Saoirse', 'Byrne', '2023-08-05', '2026-09-01', 'Patrick Byrne', 'paddy.b@example.ie', '+353 87 654 3210', 'Referral', 'offer_sent', 3, 'Full-time (5 Days)', TRUE, FALSE, 0, 'None', 'Official offer sent.'),
('Fionn', 'McCarthy', '2023-01-12', '2026-09-01', 'Niamh McCarthy', 'niamh.mc@example.ie', '+353 86 333 4444', 'Website', 'deposit_pending', 4, 'ECCE Full-time (5 Days)', FALSE, TRUE, 150.00, 'Asthma', 'Deposit received (€150).'),
('Maeve', 'Doyle', '2022-09-18', '2026-09-01', 'Sean Doyle', 'sean.doyle@example.ie', '+353 89 222 1111', 'Walk-in', 'confirmed', 4, 'ECCE Morning Session', TRUE, TRUE, 150.00, 'Peanut allergy', 'All documentation complete.')
ON CONFLICT DO NOTHING;

-- 5. Users (Staff Accounts) Table
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Activity History Logs Table
CREATE TABLE IF NOT EXISTS public.activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL REFERENCES public.applications(id) ON DELETE CASCADE,
    action TEXT NOT NULL,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) & Allow Public Read/Write for Demo
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read/write access to users" ON public.users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write access to activity_logs" ON public.activity_logs FOR ALL USING (true) WITH CHECK (true);

-- Seed Initial Admin & Manager Users
INSERT INTO public.users (email, password, role, name) VALUES
('admin@onepath.ie', 'admin123', 'admin', 'Crèche Admin'),
('manager@onepath.ie', 'manager123', 'manager', 'Crèche Manager')
ON CONFLICT (email) DO NOTHING;

